admin_side:
    path:     /
    defaults: { _controller: "AppBundle:Side:index" }

admin_side_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Side:show" }

admin_side_new:
    path:     /new
    defaults: { _controller: "AppBundle:Side:new" }

admin_side_create:
    path:     /create
    defaults: { _controller: "AppBundle:Side:create" }
    methods:  POST

admin_side_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Side:edit" }

admin_side_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Side:update" }
    methods:  [POST, PUT]

admin_side_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Side:delete" }
    methods:  [POST, DELETE]
