AppBundle\Entity\Side:
    type: entity
    table: side
    repositoryClass: AppBundle\Repository\SideRepository
    oneToMany:
        cards:
            targetEntity: Card
            orderBy: {'position':'ASC'}
            mappedBy: side
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
    uniqueConstraints:
        side_code_idx:
            columns: [ code ]
